version: '3.7'
services:
  db:
    image: postgres:13.4
    restart: always
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local