version: '3.7'
services:
  db:
    image: "postgres:13"
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
